### ISSUE TITLE
key generated with sun keytool are not portable to IBM j9 jvm 

### ISSUE THREAD

**Issue by NicolasMarcotte** [Jasig/spring-webflow-client-repo#4]
In CAS the creation of the bean of class  EncryptedTranscoder  cause the following exception on the IBM JVM
...
Caused by: java.io.IOException: com.sun.crypto.provider.SealedObjectForKeyProtector
        at com.ibm.crypto.provider.JceKeyStore.engineLoad(Unknown Source)

After some research, i have concluded that JCEKS KeyStore are not portable between JVM implementation.

I will regenerate the key with IBM keytool for me usage but it would be nice to have portability out of the box.

**Comment by mmoayyed** [comment]
Cool. thanks for reporting this. what would work for you in terms of portability?

**Comment by mmoayyed** [comment]
btw, we dont exactly support IBM's JVM. It's very much untested. We use Oracle's and OpenJDK. As a cautionary step, you "might" run into some other weird issues :)

**Comment by NicolasMarcotte** [comment]
I actually run a snapshot of cas taken somewhere between cas 3.5 and cas 4 in production on IBM J9 and it work really smoothly. I am currently preparing an upgrade to cas 4.1 and this is this only issue I encountered as CAS follows all good practice the code is living up to the java ideal of write once run anywhere :)
I was investigating the UBER keystore format from bouncy castle but I probably wont have time to implement a solution using it.

**Comment by NicolasMarcotte** [comment]
If your on IBM Academic Initiative or a similar program. You should really try that JVM as I have found that for running a tomcat on it usually takes half the memory and is around 20% faster than the one from Oracle.

**Comment by NicolasMarcotte** [comment]
just a followup to confirm that generating a key in $cas_root/WEB-INF/classes/etc/ with IBM keytool   using the following command : 
```Shell
keytool -genseckey -alias aes128 -keyalg AES -keysize 128 -storepass changeit -storetype JCEKS -keystore keystore.jceks
```
works without any problem. It's sad that symmetric keys are not portable without using a third-party lib like bouncycastle...

**Comment by mmoayyed** [comment]
Closing this issue for now; workaround reported by the reporter.
