### ISSUE TITLE
Make it easy to replace the key

### ISSUE THREAD

**Issue by NicolasMarcotte** [Jasig/spring-webflow-client-repo#6]
Including a default key in the jar is a vulnerability as this key is challenging to replace using your  documentation.

I have replaced cryptacular by nimbus-jose-jwt to make it easy to replace the key. Please have a look at https://github.com/NicolasMarcotte/spring-webflow-client-repo and if your interested I will issue you a pull request.

**Comment by mmoayyed** [comment]
Changing cryptacular is not a option, but you basically need to define a cipherbean and pass it onto EncryptedTranscoder. It will be easy to create that cipher config via Spring specially as you can just inject those into the runtime and externalize config.

**Comment by NicolasMarcotte** [comment]
ok, thanks, you should add it to the documentation ;)
Next time I update cas I will switch back to your implementation.

**Comment by mmoayyed** [comment]
I will do so, sure. In fact, I'll just modify the default CAS config to make sure it can allow you to externalize it. That should make it easier for you

**Comment by NicolasMarcotte** [comment]
Oh I saw how to externalize it when I rewrote the test for nimbus-jose-jwt instead of cryptacular. But I am sure others will appreciate it :+1:

**Comment by mmoayyed** [comment]
See https://github.com/Jasig/cas/pull/1020
